# Generated by Django 3.2.25 on 2025-11-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adherant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=100)),
                ('sexe', models.CharField(max_length=20)),
                ('situation_matrimoniale', models.CharField(max_length=50)),
                ('residence', models.CharField(max_length=100)),
                ('niveau_etude', models.CharField(max_length=100)),
                ('competences', models.CharField(max_length=255)),
                ('date_integration', models.DateField()),
                ('numero', models.CharField(max_length=8)),
                ('unite', models.CharField(max_length=100)),
                ('situation', models.CharField(max_length=100)),
                ('motif', models.CharField(max_length=100)),
                ('motivation', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='adherants/')),
                ('date_creation', models.DateField()),
            ],
        ),
    ]
