# Generated by Django 3.2.25 on 2025-11-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aderant', '0002_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='unite',
            field=models.CharField(choices=[('All', 'Tous les unités'), ('liberte', 'Unité Liberté'), ('boukoki', 'Unité Boukoki')], default='Tous les branches', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('CHEF_GROUPE', 'Chef de Groupe'), ('CHEF_UNITE', "Chef d'Unité"), ('CHEF_SECTION', 'chef de section')], default='ADMIN', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='section',
            field=models.CharField(choices=[('All', 'Tous les branches'), ('Routiere', 'Routière'), ('Cheminot', 'Chéminot'), ('Eclaireure', 'Eclaireure'), ('Louveteau', 'Louveteau')], default='Tous les branches', max_length=100),
        ),
    ]
