# Generated by Django 3.2.25 on 2025-11-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aderant', '0003_auto_20251121_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='profils/', verbose_name='Photo de profil'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='unite',
            field=models.CharField(choices=[('All', 'Tous les unités'), ('liberte', 'Unité Liberté'), ('boukoki', 'Unité Boukoki')], default='Tous les unités', max_length=100),
        ),
    ]
