# Generated by Django 3.2.25 on 2025-11-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aderant', '0004_auto_20251121_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='adherant',
            name='numero_parent',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='adherant',
            name='date_creation',
            field=models.DateField(auto_now_add=True),
        ),
    ]
