# Generated by Django 3.2.25 on 2025-11-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aderant', '0005_auto_20251125_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherant',
            name='competences',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adherant',
            name='motif',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adherant',
            name='motivation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adherant',
            name='niveau_etude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adherant',
            name='numero',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='adherant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='adherants/'),
        ),
        migrations.AlterField(
            model_name='adherant',
            name='religion',
            field=models.CharField(choices=[('islam', 'Islam'), ('christianisme', 'Christianisme')], default='islam', max_length=100),
        ),
        migrations.AlterField(
            model_name='adherant',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=20),
        ),
        migrations.AlterField(
            model_name='adherant',
            name='situation',
            field=models.CharField(choices=[('actif', 'Actif'), ('aleatoire', 'Aléatoire'), ('suspendu', 'Suspendu')], default='actif', max_length=100),
        ),
        migrations.AlterField(
            model_name='adherant',
            name='situation_matrimoniale',
            field=models.CharField(choices=[('celibataire', 'Célibataire'), ('marie', 'Marié'), ('divorce', 'Divorcé')], default='celibataire', max_length=50),
        ),
        migrations.AlterField(
            model_name='adherant',
            name='unite',
            field=models.CharField(choices=[('liberte', 'Liberté'), ('boukoki', 'Boukoki')], max_length=100),
        ),
    ]
