# Generated by Django 3.2.25 on 2026-05-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aderant', '0006_auto_20251128_1134'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adherant',
            unique_together={('nom', 'prenom', 'date_naissance', 'lieu_naissance')},
        ),
        migrations.AddIndex(
            model_name='adherant',
            index=models.Index(fields=['nom', 'prenom', 'date_naissance', 'lieu_naissance'], name='adherant_ident_idx'),
        ),
    ]
