# Generated by Django 3.2.25 on 2026-05-15 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aderant', '0007_auto_20260515_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preinscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=20)),
                ('residence', models.CharField(max_length=100)),
                ('date_integration', models.DateField()),
                ('numero', models.CharField(blank=True, max_length=8, null=True)),
                ('numero_parent', models.CharField(blank=True, max_length=8, null=True)),
                ('unite', models.CharField(choices=[('liberte', 'Liberté'), ('boukoki', 'Boukoki')], max_length=100)),
                ('motivation', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='preinscriptions/')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Validée'), ('REJECTED', 'Refusée')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_reason', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_preinscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
