# Generated by Django 3.2.25 on 2026-05-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aderant', '0008_preinscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinscription',
            name='competences',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='preinscription',
            name='motif',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preinscription',
            name='niveau_etude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preinscription',
            name='religion',
            field=models.CharField(choices=[('islam', 'Islam'), ('christianisme', 'Christianisme')], default='islam', max_length=100),
        ),
        migrations.AddField(
            model_name='preinscription',
            name='situation',
            field=models.CharField(choices=[('actif', 'Actif'), ('aleatoire', 'Aléatoire'), ('suspendu', 'Suspendu')], default='actif', max_length=100),
        ),
        migrations.AddField(
            model_name='preinscription',
            name='situation_matrimoniale',
            field=models.CharField(choices=[('celibataire', 'Célibataire'), ('marie', 'Marié'), ('divorce', 'Divorcé')], default='celibataire', max_length=50),
        ),
    ]
