"""
Django settings for scout project.

Generated by 'django-admin startproject' using Django 3.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

DEFAULT_SUPERADMIN_USERNAME = os.environ.get('DEFAULT_SUPERADMIN_USERNAME', 'ANYH')
DEFAULT_SUPERADMIN_EMAIL = os.environ.get('DEFAULT_SUPERADMIN_EMAIL', 'abdoulnasserhanki@gmail.com')
DEFAULT_SUPERADMIN_PASSWORD = os.environ.get('DEFAULT_SUPERADMIN_PASSWORD', 'AdminPass123!')
DEFAULT_SUPERADMIN_ROLE = os.environ.get('DEFAULT_SUPERADMIN_ROLE', 'ADMIN')

ALLOWED_HOSTS = [
    'maitrise-tegama.anyh-tech.com',
    'www.maitrise-tegama.anyh-tech.com',
    "groupe-tegama.onrender.com",
    'mon-projet-scout.onrender.com',
    'localhost',
    '127.0.0.1'
]

BASE_URL = os.environ.get('BASE_URL', 'https://groupe-tegama.onrender.com')

DATABASE_URL='postgresql://mon_projet_scout_db_user:IHIfQPuHe42C7TG2eXJtVLBddKfMb6VL@dpg-d86tcv37uimc73alot10-a/mon_projet_scout_db'

AUTH_USER_MODEL = 'aderant.CustomUser'

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/accueil/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9s4k)nm4d_(8z84x=mhk-d=d#dqc&&an)5whw$&!hi%#*h^r7r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

CSRF_TRUSTED_ORIGINS = [
    "https://groupe-tegama.onrender.com"
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

#ALLOWED_HOSTS = ['maitrise-tegama.anyh-tech.com', 'www.maitrise-tegama.anyh-tech.com']


# Application definition

INSTALLED_APPS = [
    'aderant',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'aderant.middleware.PasswordChangeMiddleware',  # Custom middleware for password change enforcement
]

ROOT_URLCONF = 'scout.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'scout.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL')
    )
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = '/media/'  # URL de base pour accéder aux fichiers médias
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # Chemin du système de fichiers où les fichiers sont stockés

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Logging configuration for email troubleshooting
LOG_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'scout.log'),
            'maxBytes': 1024 * 1024 * 15,  # 15MB
            'backupCount': 10,
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'aderant': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# --------------------------------------------------
# Email configuration
# Render bloque le trafic SMTP sortant sur l'offre gratuite.
# Utiliser l'API SendGrid via django-anymail pour envoyer des emails.
# Ne stockez jamais de clés secrètes en clair dans ce fichier.
# --------------------------------------------------

# Backend AnyMail (SendGrid)
INSTALLED_APPS.insert(0, 'anymail')  # Ajoute anymail au début pour s'assurer qu'il est chargé

ANYMAIL = {
    'SENDGRID_API_KEY': os.environ.get('SENDGRID_API_KEY'),
}

# Utiliser le backend AnyMail SendGrid
EMAIL_BACKEND = 'anymail.backends.sendgrid.SendGridBackend'

# Adresse d'envoi par défaut (modifiable via variable d'environnement)
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'abdoulnasserhanki@gmail.com')

# Remarque: l'ancienne configuration SMTP a été retirée car Render bloque
# le trafic SMTP sortant sur les plans gratuits. Configurez `SENDGRID_API_KEY`
# dans les variables d'environnement de votre service Render.
