"""
Django settings for scout project.

Generated by 'django-admin startproject' using Django 3.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

DEFAULT_SUPERADMIN_USERNAME = os.environ.get('DEFAULT_SUPERADMIN_USERNAME', 'ANYH')
DEFAULT_SUPERADMIN_EMAIL = os.environ.get('DEFAULT_SUPERADMIN_EMAIL', 'abdoulnasserhanki@gmail.com')
DEFAULT_SUPERADMIN_PASSWORD = os.environ.get('DEFAULT_SUPERADMIN_PASSWORD', 'AdminPass123!')
DEFAULT_SUPERADMIN_ROLE = os.environ.get('DEFAULT_SUPERADMIN_ROLE', 'ADMIN')

ALLOWED_HOSTS = [
    'maitrise-tegama.anyh-tech.com',
    'www.maitrise-tegama.anyh-tech.com',
    'mon-projet-scout.onrender.com',
    'localhost',
    '127.0.0.1'
]

BASE_URL = 'http://localhost:8000'

AUTH_USER_MODEL = 'aderant.CustomUser'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Ou votre serveur SMTP
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'abdoulnasserhanki@gmail.com'
EMAIL_HOST_PASSWORD = 'hdpx koev aavs wcmv'
DEFAULT_FROM_EMAIL = 'abdoulnasserhanki@gmail.com'


LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/accueil/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9s4k)nm4d_(8z84x=mhk-d=d#dqc&&an)5whw$&!hi%#*h^r7r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

CSRF_TRUSTED_ORIGINS = [
    "https://mon-projet-scout.onrender.com"
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

#ALLOWED_HOSTS = ['maitrise-tegama.anyh-tech.com', 'www.maitrise-tegama.anyh-tech.com']


# Application definition

INSTALLED_APPS = [
    'aderant',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'aderant.middleware.PasswordChangeMiddleware',  # Custom middleware for password change enforcement
]

ROOT_URLCONF = 'scout.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'scout.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = '/media/'  # URL de base pour accéder aux fichiers médias
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # Chemin du système de fichiers où les fichiers sont stockés

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
